<RootWidget>:
  orientation: 'vertical'
  padding: 10
  spacing: 8

  # --- Display ---
  Label:
    id: display
    text: '0'
    font_size: 48
    size_hint: 1, 0.25

  # --- Operaciones ---
  BoxLayout:
    size_hint: 1, 0.15
    spacing: 8

    Button:
      text: '+'
      font_size: 28
      on_press: root.presionar_operacion('suma')

    Button:
      text: '−'
      font_size: 28
      on_press: root.presionar_operacion('resta')

    Button:
      text: '='
      font_size: 28
      on_press: root.presionar_operacion('igual')

    Button:
      text: 'C'
      font_size: 28
      on_press: root.limpiar()

  GridLayout:
    cols:3
    spacing: 8
    size_hint: 1, 0.6
    
    Button:
      text: '1'
      font_size: 32
      on_press: root.presionar_numero('1')

    Button:
      text: '2'
      font_size: 32
      on_press: root.presionar_numero('2')

    Button:
      text: '3'
      font_size: 32
      on_press: root.presionar_numero('3')

    Button:
      text: '4'
      font_size: 32
      on_press: root.presionar_numero('4')

    Button:
      text: '5'
      font_size: 32
      on_press: root.presionar_numero('5')

    Button:
      text: '6'
      font_size: 32
      on_press: root.presionar_numero('6')

    Button:
      text: '7'
      font_size: 32
      on_press: root.presionar_numero('7')
    
    Button:
      text: '8'
      font_size: 32
      on_press: root.presionar_numero('8')
    
    Button:
      text: '9'
      font_size: 32
      on_press: root.presionar_numero('9')

    Button:
      text: '0'
      font_size: 32
      on_press: root.presionar_numero('0')
    
    


